name = "is_rectangular_cuboid2"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["IsRectangularCuboid2"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "IsRectangularCuboid2"
